package authoredorb

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

type frozenCase struct {
	Request  Request `json:"request"`
	Expected struct {
		Trades      []Trade   `json:"trades"`
		EquityCurve []float64 `json:"equityCurve"`
	} `json:"expected"`
}

func nearlyEqual(a, b float64) bool {
	return math.Abs(a-b) <= 1e-10*math.Max(1, math.Max(math.Abs(a), math.Abs(b)))
}

// These fixtures are frozen output from the app's runBacktest and the two
// authored JS strategy objects, not generated by this Go implementation.
func TestFrozenJSBrokerParity(t *testing.T) {
	paths, err := filepath.Glob("testdata/*.json")
	if err != nil || len(paths) == 0 {
		t.Fatalf("fixtures: %v (%d files)", err, len(paths))
	}
	for _, path := range paths {
		t.Run(filepath.Base(path), func(t *testing.T) {
			raw, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			var fixture frozenCase
			if err := json.Unmarshal(raw, &fixture); err != nil {
				t.Fatal(err)
			}
			got, err := Run(fixture.Request)
			if err != nil {
				t.Fatal(err)
			}
			if got.Schema != Schema || got.StrategyID != fixture.Request.StrategyID || got.Symbol != fixture.Request.Symbol || got.Timeframe != fixture.Request.Timeframe {
				t.Fatalf("result route identity differs: %+v", got)
			}
			if len(got.Trades) != len(fixture.Expected.Trades) {
				t.Fatalf("trades = %d, want %d", len(got.Trades), len(fixture.Expected.Trades))
			}
			for i, want := range fixture.Expected.Trades {
				trade := got.Trades[i]
				if trade.PositionID != want.PositionID || trade.Side != want.Side || trade.Reason != want.Reason || trade.Tag != want.Tag || trade.EntryIndex != want.EntryIndex || trade.ExitIndex != want.ExitIndex || !reflect.DeepEqual(trade.Meta, want.Meta) {
					t.Errorf("trade %d identity differs: got %+v want %+v", i, trade, want)
				}
				for field, pair := range map[string][2]float64{"entry": {trade.Entry, want.Entry}, "exit": {trade.Exit, want.Exit}, "sl": {trade.SL, want.SL}, "tp": {trade.TP, want.TP}, "initialSl": {trade.InitialSL, want.InitialSL}, "initialTp": {trade.InitialTP, want.InitialTP}, "size": {trade.Size, want.Size}, "points": {trade.Points, want.Points}, "pnl": {trade.PnL, want.PnL}, "entryT": {trade.EntryT, want.EntryT}, "exitT": {trade.ExitT, want.ExitT}} {
					if !nearlyEqual(pair[0], pair[1]) {
						t.Errorf("trade %d %s: got %.16g want %.16g", i, field, pair[0], pair[1])
					}
				}
			}
			if len(got.EquityCurve) != len(fixture.Expected.EquityCurve) {
				t.Fatalf("curve length %d", len(got.EquityCurve))
			}
			for i, want := range fixture.Expected.EquityCurve {
				if !nearlyEqual(got.EquityCurve[i], want) {
					t.Errorf("equity[%d]: got %.16g want %.16g", i, got.EquityCurve[i], want)
				}
			}
		})
	}
}

func TestRoutesAndInputs(t *testing.T) {
	raw, err := os.ReadFile("testdata/parity-held-through-session-close.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixture frozenCase
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatal(err)
	}
	req := fixture.Request
	req.Timeframe = "5m"
	if _, err := Run(req); err == nil {
		t.Fatal("parity 5m route admitted")
	}
	req.ForceRoute = true
	if _, err := Run(req); err != nil {
		t.Fatalf("forced route: %v", err)
	}
	req = fixture.Request
	req.ContextVWAP = req.ContextVWAP[:1]
	if _, err := Run(req); err == nil {
		t.Fatal("short context column admitted")
	}
	for _, tc := range []struct {
		name   string
		mutate func(*Request)
	}{
		{"inverted high-low", func(r *Request) { r.Bars[0].H = r.Bars[0].L - 1 }},
		{"open outside range", func(r *Request) { r.Bars[0].O = r.Bars[0].H + 1 }},
		{"close outside range", func(r *Request) { r.Bars[0].C = r.Bars[0].L - 1 }},
		{"negative volume", func(r *Request) { r.Bars[0].V = -1 }},
		{"nonfinite volume", func(r *Request) { r.Bars[0].V = math.NaN() }},
		{"negative fee", func(r *Request) { r.Costs.FeePerUnit = -1 }},
		{"negative slippage", func(r *Request) { r.Costs.Slippage = -1 }},
		{"negative slippage bps", func(r *Request) { r.Costs.SlippageBps = -1 }},
		{"unknown param", func(r *Request) { r.Params["unrecognized"] = 1 }},
		{"nonfinite param", func(r *Request) { r.Params["rr"] = math.NaN() }},
		{"negative risk", func(r *Request) { r.Params["riskUsd"] = -1 }},
	} {
		t.Run(tc.name, func(t *testing.T) {
			r := fixture.Request
			r.Bars = append(r.Bars[:0:0], r.Bars...)
			r.Params = Params{}
			for k, v := range fixture.Request.Params {
				r.Params[k] = v
			}
			tc.mutate(&r)
			if _, err := Run(r); err == nil {
				t.Fatal("malformed request admitted")
			}
		})
	}
}
