package dsl

import (
	"fmt"
	"math"
	"strings"
)

// fairValueGapSetupFamilies is kept separate from the generated grammar table
// until the JS grammar manifest is regenerated by the coordinator lane. This
// lets the Go parser accept the new family without hand-editing generated
// provenance data.
var fairValueGapSetupFamilies = map[string]string{
	"fair value gap": string(FamilyFairValueGap),
	"fairvaluegap":   string(FamilyFairValueGap),
	"fvg":            string(FamilyFairValueGap),
}

var fairValueGapSetupTypePhrases = []string{
	"fair value gap",
	"fairvaluegap",
	"fvg",
}

func (p *parser) parseFairValueGapGap(line logicalLine, tokens []string) {
	if p.config["setupType"] != string(FamilyFairValueGap) || len(tokens) < 3 || !strings.EqualFold(tokens[1], "minimum") {
		return
	}
	if !isNumberToken(tokens[2]) || (len(tokens) > 3 && !strings.EqualFold(tokens[3], "atr")) {
		p.err(line, "fair value gap minimum must be written as `gap minimum X ATR` with a finite positive X", "gap minimum X ATR")
		return
	}
	value := parseNumber(tokens[2], 0)
	if !isFiniteNumber(value) || value <= 0 {
		p.err(line, "fair value gap minimum must be finite and positive", "gap minimum X ATR")
		return
	}
	fvg := copyMap(p.config["fairValueGap"])
	fvg["minGapAtr"] = value
	p.config["fairValueGap"] = fvg
}

func (p *parser) parseFairValueGapSweep(line logicalLine, tokens []string) {
	if p.config["setupType"] != string(FamilyFairValueGap) || len(tokens) < 2 {
		return
	}
	fvg := copyMap(p.config["fairValueGap"])
	switch strings.ToLower(tokens[1]) {
	case "required":
		fvg["sweepRequired"] = 1.0
		fvg["sweepLookbackCandles"] = 30.0
		for i := 2; i < len(tokens); i++ {
			if strings.EqualFold(tokens[i], "within") {
				if i+1 >= len(tokens) || !isNumberToken(tokens[i+1]) {
					p.err(line, "fair value gap sweep window must be written as `sweep required within N candles` with a positive integer N", "sweep required within N candles")
					return
				}
				value := parseNumber(tokens[i+1], 0)
				if !isFiniteNumber(value) || value <= 0 || value != math.Trunc(value) {
					p.err(line, "fair value gap sweep window must be a positive integer", "sweep required within N candles")
					return
				}
				fvg["sweepLookbackCandles"] = value
			}
		}
	case "off":
		fvg["sweepRequired"] = 0.0
	case "pivot":
		if len(tokens) < 3 || !isNumberToken(tokens[2]) {
			p.err(line, "fair value gap sweep pivot must be written as `sweep pivot N candles` with a positive integer N", "sweep pivot N candles")
			return
		}
		value := parseNumber(tokens[2], 0)
		if !isFiniteNumber(value) || value <= 0 || value != math.Trunc(value) {
			p.err(line, "fair value gap sweep pivot width must be a positive integer", "sweep pivot N candles")
			return
		}
		fvg["sweepPivotWidth"] = value
	default:
		p.err(line, "fair value gap sweep phrases are: sweep required [within N candles] | sweep off | sweep pivot N candles", "sweep required within 30 candles")
		return
	}
	p.config["fairValueGap"] = fvg
}

func (p *parser) parseFairValueGapDisplacement(line logicalLine, tokens []string) {
	if p.config["setupType"] != string(FamilyFairValueGap) || len(tokens) < 3 || !strings.EqualFold(tokens[1], "minimum") {
		return
	}
	if !isNumberToken(tokens[2]) || (len(tokens) > 3 && !strings.EqualFold(tokens[3], "atr")) {
		p.err(line, "fair value gap displacement minimum must be written as `displacement minimum X ATR` with a finite positive X", "displacement minimum X ATR")
		return
	}
	value := parseNumber(tokens[2], 0)
	if !isFiniteNumber(value) || value <= 0 {
		p.err(line, "fair value gap displacement minimum must be finite and positive", "displacement minimum X ATR")
		return
	}
	fvg := copyMap(p.config["fairValueGap"])
	fvg["minDisplacementAtr"] = value
	p.config["fairValueGap"] = fvg
}

func (p *parser) validateFairValueGap() {
	if p.config["setupType"] != string(FamilyFairValueGap) {
		return
	}
	fvg := copyMap(p.config["fairValueGap"])
	for key, label := range map[string]string{
		"minGapAtr":          "gap minimum",
		"minDisplacementAtr": "displacement minimum",
	} {
		value := fairValueGapNumber(fvg[key])
		if !isFiniteNumber(value) || value <= 0 {
			p.errorAt(nil, nil, fmt.Sprintf("fair value gap %s must be finite and positive", label), "")
		}
	}
	retest := fairValueGapNumber(fvg["retestCandles"])
	if !isFiniteNumber(retest) || retest <= 0 || retest != math.Trunc(retest) {
		p.errorAt(nil, nil, "fair value gap retest window must be a positive integer", "retest within N candles")
	}
	if _, present := fvg["entryExpireCandles"]; present {
		entryExpiry := fairValueGapNumber(fvg["entryExpireCandles"])
		if !isFiniteNumber(entryExpiry) || entryExpiry <= 0 || entryExpiry != math.Trunc(entryExpiry) {
			p.errorAt(nil, nil, "fair value gap entry window must be a positive integer", "entry at midpoint within N candles")
		}
	}
	for key, label := range map[string]string{
		"sweepLookbackCandles": "sweep window",
		"sweepPivotWidth":      "sweep pivot width",
	} {
		if _, present := fvg[key]; !present {
			continue
		}
		value := fairValueGapNumber(fvg[key])
		if !isFiniteNumber(value) || value <= 0 || value != math.Trunc(value) {
			p.errorAt(nil, nil, fmt.Sprintf("fair value gap %s must be a positive integer", label), "")
		}
	}
	entryReference, _ := fvg["entryReference"].(string)
	if entryReference != "midpoint" && entryReference != "proximalEdge" && entryReference != "fib618" {
		p.errorAt(nil, nil, fmt.Sprintf("fair value gap entry reference %q is unsupported", entryReference), "entry at midpoint")
	}
}

func fairValueGapNumber(value any) float64 {
	switch typed := value.(type) {
	case float64:
		return typed
	case float32:
		return float64(typed)
	case int:
		return float64(typed)
	case int64:
		return float64(typed)
	default:
		return math.NaN()
	}
}
